"""
clarification_engine.py — Clarification Loop Engine (Phase 12)

Manages the pre-execution clarification dialogue between the system and clinician.

Responsibilities:
  1. Format clarification questions for API response
  2. Validate submitted answers
  3. Merge answers back into the enriched query string
  4. Determine if clarification is now resolved

Design:
  - No LLM calls — pure logic
  - Questions are pre-generated by InformationSufficiencyEngine
  - Engine handles answer merging + enrichment
  - Max clarification iterations enforced here

Usage:
  from backend.decision.clarification_engine import (
      format_questions_for_api, resolve_clarification, is_clarification_resolved
  )
"""
from __future__ import annotations

from typing import Dict, List, Optional

from backend.decision.execution_plan import ClarificationQuestion, QuestionPriority
from backend.utils.logger import logger


# ── Configuration ─────────────────────────────────────────────────────────────
MAX_CLARIFICATION_ITERATIONS = 3   # safety limit on clarification loops


# ═════════════════════════════════════════════════════════════════════════════
# Question Formatting
# ═════════════════════════════════════════════════════════════════════════════

def format_questions_for_api(
    questions: List[ClarificationQuestion],
) -> List[Dict]:
    """
    Serialize ClarificationQuestion list for API response.
    Returns a plain dict list suitable for JSON serialization.
    """
    result = []
    for q in questions:
        result.append({
            "question_id":       q.question_id,
            "question_text":     q.question_text,
            "category":          q.category if isinstance(q.category, str) else q.category.value,
            "priority":          q.priority if isinstance(q.priority, str) else q.priority.value,
            "expected_format":   q.expected_format,
            "choices":           q.choices,
            "hint":              q.hint,
            "default_if_skipped": q.default_if_skipped,
        })
    return result


# ═════════════════════════════════════════════════════════════════════════════
# Answer Validation
# ═════════════════════════════════════════════════════════════════════════════

def validate_answers(
    questions:    List[ClarificationQuestion],
    answers:      Dict[str, str],
) -> Dict[str, str]:
    """
    Validate submitted answers against question schemas.
    Returns a dict of {question_id: error_message} for invalid answers.
    Only validates format (numeric questions must have numeric values).
    """
    errors: Dict[str, str] = {}
    for q in questions:
        answer = answers.get(q.question_id, "").strip()
        if not answer:
            continue  # unanswered — handled by resolution logic

        if q.expected_format == "numeric":
            # Extract any numeric portion
            import re
            if not re.search(r"\d", answer):
                errors[q.question_id] = f"Expected a numeric value for '{q.question_text[:40]}'"

        elif q.expected_format == "choice" and q.choices:
            answer_lower = answer.lower()
            valid = any(c.lower() in answer_lower or answer_lower in c.lower() for c in q.choices)
            if not valid:
                errors[q.question_id] = (
                    f"Expected one of: {', '.join(q.choices)} for '{q.question_text[:40]}'"
                )

    return errors


# ═════════════════════════════════════════════════════════════════════════════
# Clarification Resolution
# ═════════════════════════════════════════════════════════════════════════════

def is_clarification_resolved(
    questions:    List[ClarificationQuestion],
    answers:      Dict[str, str],
    strict:       bool = False,
) -> bool:
    """
    Determine if clarification is sufficiently resolved to proceed.

    Args:
        questions:  The pending clarification questions.
        answers:    Dict of {question_id: answer_text}.
        strict:     If True, ALL questions must be answered.
                    If False (default), only CRITICAL questions must be answered.

    Returns:
        True if resolved enough to proceed.
    """
    if not questions:
        return True  # No questions = already resolved

    for q in questions:
        qid    = q.question_id
        answer = answers.get(qid, "").strip()
        priority = q.priority if isinstance(q.priority, str) else q.priority.value

        if not answer and priority == QuestionPriority.CRITICAL.value:
            if strict:
                return False
            # Non-strict: critical questions with defaults can use the default
            if not q.default_if_skipped:
                return False

        if strict and not answer:
            return False

    return True


def resolve_clarification(
    original_query:  str,
    questions:       List[ClarificationQuestion],
    answers:         Dict[str, str],
) -> str:
    """
    Merge clarification answers into the original query to produce
    an enriched query string.

    Strategy:
      - Append answered questions as structured context at the end of the query.
      - Unanswered optional questions: use default_if_skipped if available.
      - Unanswered critical questions: add caveat note.

    Returns:
        Enriched query string with context appended.
    """
    if not questions or not answers:
        return original_query

    clarification_lines = []
    caveat_elements = []

    for q in questions:
        qid    = q.question_id
        answer = answers.get(qid, "").strip()
        priority = q.priority if isinstance(q.priority, str) else q.priority.value

        if answer:
            category = q.category if isinstance(q.category, str) else q.category.value
            clarification_lines.append(f"[{category.upper()}] {q.question_text}: {answer}")
        elif q.default_if_skipped:
            clarification_lines.append(
                f"[{q.category if isinstance(q.category, str) else q.category.value}] "
                f"{q.question_text}: {q.default_if_skipped} (default)"
            )
        elif priority == QuestionPriority.CRITICAL.value:
            caveat_elements.append(q.question_text)

    if not clarification_lines:
        return original_query

    enriched = original_query.strip()
    enriched += "\n\n[CLARIFICATION CONTEXT PROVIDED BY CLINICIAN]\n"
    enriched += "\n".join(clarification_lines)

    if caveat_elements:
        enriched += (
            "\n\n[WARNING: The following critical information was not provided: "
            + "; ".join(caveat_elements) + "]"
        )

    logger.info(
        f"[ClarificationEngine] Enriched query with {len(clarification_lines)} answers. "
        f"Missing critical: {len(caveat_elements)}"
    )
    return enriched


# ═════════════════════════════════════════════════════════════════════════════
# Iteration Guard
# ═════════════════════════════════════════════════════════════════════════════

def should_skip_clarification(
    replan_count:        int,
    clarification_count: int,
    risk_level:          str,
) -> bool:
    """
    Determine if clarification should be skipped.

    Skips clarification if:
      - Risk level is CRITICAL (emergency bypass)
      - Clarification iteration limit reached
    """
    if risk_level == "critical":
        logger.info("[ClarificationEngine] CRITICAL risk — skipping clarification.")
        return True
    if clarification_count >= MAX_CLARIFICATION_ITERATIONS:
        logger.warning(
            f"[ClarificationEngine] Max clarification iterations "
            f"({MAX_CLARIFICATION_ITERATIONS}) reached — proceeding."
        )
        return True
    return False
