"""
execution_plan.py — First-Class Orchestration Objects (Phase 12)

This module defines the ExecutionPlan and all its constituent schemas.
An ExecutionPlan is a first-class orchestration object produced by the
OrchestrationPlanner BEFORE any agent executes.

Design:
  - Pure data schemas only — no business logic, no LLM calls, no imports
    from other backend modules (prevents circular imports).
  - All types are Pydantic models + Enums for schema validation + serialisation.
  - The ExecutionPlan is stored in AgentState["execution_plan"] as a dict
    (serialised via .model_dump()) so it survives LangGraph state merges.

Usage:
  from backend.decision.execution_plan import (
      ExecutionPlan, ClinicalIntent, ClarificationQuestion,
      ExecutionStep, EvidenceStrategy, GovernancePolicy,
  )
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ═════════════════════════════════════════════════════════════════════════════
# Enums
# ═════════════════════════════════════════════════════════════════════════════

class ClinicalIntent(str, Enum):
    """What the clinician is trying to achieve."""
    EMERGENCY_TRIAGE       = "emergency_triage"
    DIAGNOSTIC_WORKUP      = "diagnostic_workup"
    TREATMENT_PLANNING     = "treatment_planning"
    MEDICATION_REVIEW      = "medication_review"
    RESEARCH_LOOKUP        = "research_lookup"
    LITERATURE_SYNTHESIS   = "literature_synthesis"
    SIMILAR_CASE_SEARCH    = "similar_case_search"
    RISK_STRATIFICATION    = "risk_stratification"
    MONITORING_FOLLOW_UP   = "monitoring_follow_up"
    UNKNOWN                = "unknown"


class QuestionPriority(str, Enum):
    CRITICAL  = "critical"    # Must answer before proceeding
    IMPORTANT = "important"   # Strongly recommended
    OPTIONAL  = "optional"    # Helpful but skippable


class QuestionCategory(str, Enum):
    DEMOGRAPHICS  = "demographics"    # age, gender, weight
    VITALS        = "vitals"          # BP, HR, O2, temp, RR
    CHIEF_COMPLAINT = "chief_complaint"
    SYMPTOMS      = "symptoms"
    HISTORY       = "history"         # PMH, surgical history
    MEDICATIONS   = "medications"
    ALLERGIES     = "allergies"
    LABS          = "labs"            # troponin, CBC, BMP, etc.
    IMAGING       = "imaging"         # ECG, X-ray, CT
    TIMELINE      = "timeline"        # onset, duration


class RetrievalDepth(str, Enum):
    SHALLOW  = "shallow"    # fast, 3-5 docs
    STANDARD = "standard"  # default, 5-8 docs
    DEEP     = "deep"       # thorough, 8-15 docs


class RePlanTrigger(str, Enum):
    EVIDENCE_QUALITY_DROP  = "evidence_quality_drop"
    CONTRADICTION_DETECTED = "contradiction_detected"
    CONFIDENCE_LOW         = "confidence_trending_low"
    MULTIMODAL_POOR        = "multimodal_quality_poor"
    RETRIEVAL_INSUFFICIENT = "retrieval_insufficient"
    VALIDATION_FAILED      = "validation_failed"


class AgentCapability(str, Enum):
    """Orchestration capability identifiers (map to agent nodes)."""
    QUERY_UNDERSTANDING  = "query_understanding"   # query_agent
    SEMANTIC_RETRIEVAL   = "semantic_retrieval"    # retrieval_agent (semantic)
    GRAPH_RETRIEVAL      = "graph_retrieval"       # retrieval_agent (graph)
    RESEARCH_RETRIEVAL   = "research_retrieval"    # retrieval_agent (live research)
    SIMILAR_CASE_LOOKUP  = "similar_case_lookup"   # retrieval_agent (cases)
    MULTIMODAL_ANALYSIS  = "multimodal_analysis"   # image analysis (pre-ingested)
    CLINICAL_REASONING   = "clinical_reasoning"    # reasoning_agent
    EVIDENCE_EVALUATION  = "evidence_evaluation"   # evidence_evaluator
    CONTRADICTION_CHECK  = "contradiction_check"   # contradiction_analyzer
    VALIDATION           = "validation"            # validation_agent
    REFLECTION           = "reflection"            # reflection_agent
    GOVERNANCE           = "governance"            # supervisor finalize


# ═════════════════════════════════════════════════════════════════════════════
# Component Models
# ═════════════════════════════════════════════════════════════════════════════

class ClarificationQuestion(BaseModel):
    """A targeted clarification question generated by the planner."""
    question_id:       str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    question_text:     str
    category:          QuestionCategory
    priority:          QuestionPriority
    expected_format:   str  = "freetext"    # freetext | numeric | boolean | choice
    choices:           List[str] = Field(default_factory=list)  # for choice format
    hint:              str  = ""            # clinical guidance for answering
    default_if_skipped: Optional[str] = None

    class Config:
        use_enum_values = True


class ExecutionStep(BaseModel):
    """A single step in the dynamic execution plan."""
    step_id:          str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    capability:       AgentCapability
    required:         bool  = True
    depends_on:       List[str] = Field(default_factory=list)  # step_ids
    retry_limit:      int  = 2
    timeout_seconds:  int  = 30
    fallback_strategy: str = "skip"   # skip | use_cached | escalate
    rationale:        str  = ""       # why this step was included

    class Config:
        use_enum_values = True


class EvidenceStrategy(BaseModel):
    """Which evidence sources to activate and how deeply."""
    use_graph:          bool = False
    use_semantic:       bool = True
    use_research:       bool = False
    use_multimodal:     bool = False
    use_similar_cases:  bool = False
    retrieval_depth:    RetrievalDepth = RetrievalDepth.STANDARD
    source_priority:    List[str] = Field(default_factory=lambda: ["guideline", "rct", "semantic"])
    min_sources:        int  = 3     # minimum acceptable sources

    class Config:
        use_enum_values = True


class GovernancePolicy(BaseModel):
    """Governance and escalation configuration for this execution."""
    escalation_threshold:   float = 0.55
    require_human_review:   bool  = False
    review_severity:        str   = "standard"   # standard | urgent | critical
    audit_level:            str   = "standard"   # standard | enhanced
    max_confidence_gap:     float = 0.25  # gap between raw and validated score


class PatientContext(BaseModel):
    """Structured patient data extracted from the query."""
    age:              Optional[str] = None
    gender:           Optional[str] = None
    chief_complaint:  Optional[str] = None
    symptom_duration: Optional[str] = None
    vitals_present:   bool = False
    medications_present: bool = False
    allergies_present:   bool = False
    history_present:     bool = False
    ecg_present:         bool = False
    labs_present:        bool = False
    imaging_present:     bool = False
    extracted_conditions: List[str] = Field(default_factory=list)
    extracted_medications: List[str] = Field(default_factory=list)
    extracted_vitals:     Dict[str, str] = Field(default_factory=dict)


# ═════════════════════════════════════════════════════════════════════════════
# Top-Level ExecutionPlan
# ═════════════════════════════════════════════════════════════════════════════

class ExecutionPlan(BaseModel):
    """
    First-class orchestration object produced by the OrchestrationPlanner.

    This plan is created BEFORE any agent executes and stored in AgentState
    as a serialised dict. It governs the entire execution.

    Key fields:
      - clinical_intent: what the clinician is trying to achieve
      - goal: human-readable goal description
      - patient_context: structured extracted patient data
      - required_capabilities + optional_capabilities: dynamic agent selection
      - execution_steps: ordered steps with dependencies
      - evidence_strategy: which retrieval sources to activate
      - clarification_required: whether to pause for clarification
      - clarification_questions: targeted questions if needed
      - governance_policy: escalation and review configuration
    """
    plan_id:          str = Field(default_factory=lambda: str(uuid.uuid4()))
    created_at:       str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    schema_version:   str = "12.0"

    # ── Intent + Goal ─────────────────────────────────────────────────────────
    clinical_intent:  ClinicalIntent = ClinicalIntent.UNKNOWN
    goal:             str  = ""         # human-readable: "evaluate_possible_stemi"
    goal_description: str  = ""         # longer explanation

    # ── Patient Context ───────────────────────────────────────────────────────
    patient_context:  PatientContext = Field(default_factory=PatientContext)

    # ── Agent Capabilities ────────────────────────────────────────────────────
    required_capabilities: List[AgentCapability] = Field(
        default_factory=lambda: [
            AgentCapability.QUERY_UNDERSTANDING,
            AgentCapability.SEMANTIC_RETRIEVAL,
            AgentCapability.CLINICAL_REASONING,
            AgentCapability.EVIDENCE_EVALUATION,
            AgentCapability.VALIDATION,
            AgentCapability.GOVERNANCE,
        ]
    )
    optional_capabilities: List[AgentCapability] = Field(default_factory=list)
    excluded_capabilities: List[AgentCapability] = Field(default_factory=list)

    # ── Execution Sequence ────────────────────────────────────────────────────
    execution_steps:  List[ExecutionStep] = Field(default_factory=list)

    # ── Evidence Strategy ─────────────────────────────────────────────────────
    evidence_strategy: EvidenceStrategy = Field(default_factory=EvidenceStrategy)

    # ── Clarification ─────────────────────────────────────────────────────────
    clarification_required:  bool = False
    clarification_questions: List[ClarificationQuestion] = Field(default_factory=list)
    clarification_resolved:  bool = False
    missing_information:     List[str] = Field(default_factory=list)
    proceed_with_caveat:     str  = ""  # warning if proceeding without clarification

    # ── Governance ────────────────────────────────────────────────────────────
    governance_policy:       GovernancePolicy = Field(default_factory=GovernancePolicy)

    # ── Adaptive Re-planning ──────────────────────────────────────────────────
    replan_triggers:         List[RePlanTrigger] = Field(
        default_factory=lambda: [
            RePlanTrigger.EVIDENCE_QUALITY_DROP,
            RePlanTrigger.CONTRADICTION_DETECTED,
            RePlanTrigger.CONFIDENCE_LOW,
        ]
    )
    max_replan_iterations:   int  = 3

    # ── Risk (mirrors existing RiskLevel for quick access) ────────────────────
    risk_level_value:        str  = "low"   # mirror of RiskAssessment.level.value
    risk_score:              float = 0.0
    emergency_override:      bool  = False  # True = CRITICAL risk, skip clarification

    # ── Trace ─────────────────────────────────────────────────────────────────
    plan_trace:              Dict[str, Any] = Field(default_factory=dict)

    class Config:
        use_enum_values = True

    def to_summary_dict(self) -> Dict[str, Any]:
        """Compact summary suitable for API response."""
        return {
            "plan_id":              self.plan_id,
            "clinical_intent":      self.clinical_intent,
            "goal":                 self.goal,
            "required_capabilities": [c for c in self.required_capabilities],
            "optional_capabilities": [c for c in self.optional_capabilities],
            "evidence_strategy":    {
                "use_graph":        self.evidence_strategy.use_graph,
                "use_research":     self.evidence_strategy.use_research,
                "use_similar_cases": self.evidence_strategy.use_similar_cases,
                "use_multimodal":   self.evidence_strategy.use_multimodal,
                "retrieval_depth":  self.evidence_strategy.retrieval_depth,
            },
            "clarification_required": self.clarification_required,
            "missing_information":   self.missing_information,
            "risk_level":           self.risk_level_value,
            "risk_score":           self.risk_score,
            "emergency_override":   self.emergency_override,
            "max_replan_iterations": self.max_replan_iterations,
            "schema_version":       self.schema_version,
        }
